version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules


services:
  cataloger_db:
    image: "postgres:11"
    restart: always
    env_file:
      - .env
    networks:
      - cataloger
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "backup:/backups"

  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "cataloger-development"
    depends_on:
      - cataloger_db
    networks:
      - cataloger
    ports:
      - "0.0.0.0:5020:5020"
      - "0.0.0.0:2992:2992"
    <<: *default_volumes

  flask-prod:
    restart: always
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "cataloger-production"
    depends_on:
      - cataloger_db
    networks:
      - cataloger
    ports:
      - "127.0.0.1:5020:5020"
    restart: always
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes
    restart: always

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "cataloger-manage"
    depends_on:
      - cataloger_db
    networks:
      - cataloger
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
  static-build:
  db_data:
    driver_opts:
      type: none
      device: $HOME/data/cataloger
      o: bind

  backup:
    driver_opts:
      type: none
      device: $HOME/data/backups/omero
      o: bind

networks:
  cataloger:
