"""empty message

Revision ID: 29c6fc149ecc
Revises: e168e30a2edf
Create Date: 2020-08-11 14:29:31.458018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c6fc149ecc'
down_revision = 'e168e30a2edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marker_card',
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['marker_id'], ['markers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marker_card')
    # ### end Alembic commands ###
