"""empty message

Revision ID: e0a8d68da708
Revises: 57c2b109eec1
Create Date: 2021-06-14 11:58:54.807120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a8d68da708'
down_revision = '57c2b109eec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'organism_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'organism_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
