"""empty message

Revision ID: eee22464128b
Revises: 99da667cf1a0
Create Date: 2020-09-09 13:12:30.983163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee22464128b'
down_revision = '99da667cf1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'methods', ['method_id'], ['id'])
    op.add_column('genes', sa.Column('organism_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'genes', 'organisms', ['organism_id'], ['id'])
    op.add_column('markers', sa.Column('organism_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'markers', 'organisms', ['organism_id'], ['id'])
    op.add_column('processes', sa.Column('organism_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'processes', 'organisms', ['organism_id'], ['id'])
    op.add_column('samples', sa.Column('organism_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'samples', 'organisms', ['organism_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_column('samples', 'organism_id')
    op.drop_constraint(None, 'processes', type_='foreignkey')
    op.drop_column('processes', 'organism_id')
    op.drop_constraint(None, 'markers', type_='foreignkey')
    op.drop_column('markers', 'organism_id')
    op.drop_constraint(None, 'genes', type_='foreignkey')
    op.drop_column('genes', 'organism_id')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'method_id')
    # ### end Alembic commands ###
